name: PR Checks

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/android-setup.yaml
    with:
      task: assembleDebug

  ktlint:
    uses: ./.github/workflows/android-setup.yaml
    with:
      task: ktlintCheck
      show-ktlint-errors: true

  detekt:
    uses: ./.github/workflows/android-setup.yaml
    with:
      task: detekt

  unit-tests:
    uses: ./.github/workflows/android-setup.yaml
    with:
      task: testDebugUnitTest
